version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - laravel

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_test_runner
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    command: ["php", "artisan", "test"]
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
